
/**
 * GridColumn Sizes for Layout.Grid control
 * @date 24/12/2022 - 17:19:43
 *
 * @export
 * @enum {number}
 */
export enum Mrbr_UI_Bootstrap_Layout_GridColumnSizes {
    col = "col",
    colSm = "col-sm",
    colMd = "col-md",
    colLg = "col-lg",
    colXl = "col-xl",
    colXxl = "col-xxl",
    colAuto = "col-auto",
    colSmAuto = "col-sm-auto",
    colMdAuto = "col-md-auto",
    colLgAuto = "col-lg-auto",
    colXlAuto = "col-xl-auto",
    colXxlAuto = "col-xxl-auto",
    col1 = "col-1",
    colSm1 = "col-sm-1",
    colMd1 = "col-md-1",
    colLg1 = "col-lg-1",
    colXl1 = "col-xl-1",
    colXxl1 = "col-xxl-1",
    col2 = "col-2",
    colSm2 = "col-sm-2",
    colMd2 = "col-md-2",
    colLg2 = "col-lg-2",
    colXl2 = "col-xl-2",
    colXxl2 = "col-xxl-2",
    col3 = "col-3",
    colSm3 = "col-sm-3",
    colMd3 = "col-md-3",
    colLg3 = "col-lg-3",
    colXl3 = "col-xl-3",
    colXxl3 = "col-xxl-3",
    col4 = "col-4",
    colSm4 = "col-sm-4",
    colMd4 = "col-md-4",
    colLg4 = "col-lg-4",
    colXl4 = "col-xl-4",
    colXxl4 = "col-xxl-4",
    col5 = "col-5",
    colSm5 = "col-sm-5",
    colMd5 = "col-md-5",
    colLg5 = "col-lg-5",
    colXl5 = "col-xl-5",
    colXxl5 = "col-xxl-5",
    col6 = "col-6",
    colSm6 = "col-sm-6",
    colMd6 = "col-md-6",
    colLg6 = "col-lg-6",
    colXl6 = "col-xl-6",
    colXxl6 = "col-xxl-6",
    col7 = "col-7",
    colSm7 = "col-sm-7",
    colMd7 = "col-md-7",
    colLg7 = "col-lg-7",
    colXl7 = "col-xl-7",
    colXxl7 = "col-xxl-7",
    col8 = "col-8",
    colSm8 = "col-sm-8",
    colMd8 = "col-md-8",
    colLg8 = "col-lg-8",
    colXl8 = "col-xl-8",
    colXxl8 = "col-xxl-8",
    col9 = "col-9",
    colSm9 = "col-sm-9",
    colMd9 = "col-md-9",
    colLg9 = "col-lg-9",
    colXl9 = "col-xl-9",
    colXxl9 = "col-xxl-9",
    col10 = "col-10",
    colSm10 = "col-sm-10",
    colMd10 = "col-md-10",
    colLg10 = "col-lg-10",
    colXl10 = "col-xl-10",
    colXxl10 = "col-xxl-10",
    col11 = "col-11",
    colSm11 = "col-sm-11",
    colMd11 = "col-md-11",
    colLg11 = "col-lg-11",
    colXl11 = "col-xl-11",
    colXxl11 = "col-xxl-11",
    col12 = "col-12",
    colSm12 = "col-sm-12",
    colMd12 = "col-md-12",
    colLg12 = "col-lg-12",
    colXl12 = "col-xl-12",
    colXxl12 = "col-xxl-12"
}