export enum Mrbr_UI_Bootstrap_Layout_Gutters {
    x0 = "gx-0",
    x1 = "gx-1",
    x2 = "gx-2",
    x3 = "gx-3",
    x4 = "gx-4",
    x5 = "gx-5",
    y0 = "gy-0",
    y1 = "gy-1",
    y2 = "gy-2",
    y3 = "gy-3",
    y4 = "gy-4",
    y5 = "gy-5",
    xy0 = "g-0",
    xy1 = "g-1",
    xy2 = "g-2",
    xy3 = "g-3",
    xy4 = "g-4",
    xy5 = "g-5",
    default = ""
}
