export enum Mrbr_UI_Bootstrap_Utilities_Display {

    none = "d-none",

    xsNone = "d-none",
    xsInline = "d-inline",
    xsInlineBlock = "d-inline-block",
    xsBlock = "d-block",
    xsGrid = "d-grid",
    xsTable = "d-table",
    xsTableCell = "d-table-cell",
    xsTableRow = "d-table-row",
    xsFlex = "d-flex",
    xsInlineFlex = "d-inline-flex",

    smNone = "d-sm-none",
    smInline = "d-sm-inline",
    smInlineBlock = "d-sm-inline-block",
    smBlock = "d-sm-block",
    smGrid = "d-sm-grid",
    smTable = "d-sm-table",
    smTableCell = "d-sm-table-cell",
    smTableRow = "d-sm-table-row",
    smFlex = "d-sm-flex",
    smInlineFlex = "d-sm-inline-flex",

    mdNone = "d-md-none",
    mdInline = "d-md-inline",
    mdInlineBlock = "d-md-inline-block",
    mdBlock = "d-md-block",
    mdGrid = "d-md-grid",
    mdTable = "d-md-table",
    mdTableCell = "d-md-table-cell",
    mdTableRow = "d-md-table-row",
    mdFlex = "d-md-flex",
    mdInlineFlex = "d-md-inline-flex",

    lgNone = "d-lg-none",
    lgInline = "d-lg-inline",
    lgInlineBlock = "d-lg-inline-block",
    lgBlock = "d-lg-block",
    lgGrid = "d-lg-grid",
    lgTable = "d-lg-table",
    lgTableCell = "d-lg-table-cell",
    lgTableRow = "d-lg-table-row",
    lgFlex = "d-lg-flex",
    lgInlineFlex = "d-lg-inline-flex",

    xlNone = "d-xl-none",
    xlInline = "d-xl-inline",
    xlInlineBlock = "d-xl-inline-block",
    xlBlock = "d-xl-block",
    xlGrid = "d-xl-grid",
    xlTable = "d-xl-table",
    xlTableCell = "d-xl-table-cell",
    xlTableRow = "d-xl-table-row",
    xlFlex = "d-xl-flex",
    xlInlineFlex = "d-xl-inline-flex",

    xxlNone = "d-xxl-none",
    xxlInline = "d-xxl-inline",
    xxlInlineBlock = "d-xxl-inline-block",
    xxlBlock = "d-xxl-block",
    xxlGrid = "d-xxl-grid",
    xxlTable = "d-xxl-table",
    xxlTableCell = "d-xxl-table-cell",
    xxlTableRow = "d-xxl-table-row",
    xxlFlex = "d-xxl-flex",
    xxlInlineFlex = "d-xxl-inline-flex",

    printNone = "d-print-none",
    printInline = "d-print-inline",
    printInlineBlock = "d-print-inline-block",
    printBlock = "d-print-block",
    printGrid = "d-print-grid",
    printTable = "d-print-table",
    printTableCell = "d-print-table-cell",
    printTableRow = "d-print-table-row",
    printFlex = "d-print-flex",
    printInlineFlex = "d-print-inline-flex",
}