export enum Mrbr_UI_Bootstrap_Controls_Utilities_Flex$AlignContent {
    //  Align Content
    alignContentStart = "align-content-start",
    alignContentEnd = "align-content-end",
    alignContentCenter = "align-content-center",
    alignContentAround = "align-content-around",
    alignContentStretch = "align-content-stretch",
    alignContentSmStart = "align-content-sm-start",
    alignContentSmEnd = "align-content-sm-end",
    alignContentSmCenter = "align-content-sm-center",
    alignContentSmAround = "align-content-sm-around",
    alignContentSmStretch = "align-content-sm-stretch",
    alignContentMdStart = "align-content-md-start",
    alignContentMdEnd = "align-content-md-end",
    alignContentMdCenter = "align-content-md-center",
    alignContentMdAround = "align-content-md-around",
    alignContentMdStretch = "align-content-md-stretch",
    alignContentLgStart = "align-content-lg-start",
    alignContentLgEnd = "align-content-lg-end",
    alignContentLgCenter = "align-content-lg-center",
    alignContentLgAround = "align-content-lg-around",
    alignContentLgStretch = "align-content-lg-stretch",
    alignContentXlStart = "align-content-xl-start",
    alignContentXlEnd = "align-content-xl-end",
    alignContentXlCenter = "align-content-xl-center",
    alignContentXlAround = "align-content-xl-around",
    alignContentXlStretch = "align-content-xl-stretch",
    alignContentXxlStart = "align-content-xxl-start",
    alignContentXxlEnd = "align-content-xxl-end",
    alignContentXxlCenter = "align-content-xxl-center",
    alignContentXxlAround = "align-content-xxl-around",
    alignContentXxlStretch = "align-content-xxl-stretch",

}