export enum Mrbr_UI_Bootstrap_Controls_Utilities_lex$AlignItems {
    //  Align Items
    alignItemsstart = "align-items-start",
    alignItemsend = "align-items-end",
    alignItemscenter = "align-items-center",
    alignItemsbaseline = "align-items-baseline",
    alignItemsstretch = "align-items-stretch",
    alignItemsSmStart = "align-items-sm-start",
    alignItemsSmEnd = "align-items-sm-end",
    alignItemsSmCenter = "align-items-sm-center",
    alignItemsSmBaseline = "align-items-sm-baseline",
    alignItemsSmStretch = "align-items-sm-stretch",
    alignItemsMdStart = "align-items-md-start",
    alignItemsMdEnd = "align-items-md-end",
    alignItemsMdCenter = "align-items-md-center",
    alignItemsMdBaseline = "align-items-md-baseline",
    alignItemsMdStretch = "align-items-md-stretch",
    alignItemsLgStart = "align-items-lg-start",
    alignItemsLgEnd = "align-items-lg-end",
    alignItemsLgCenter = "align-items-lg-center",
    alignItemsLgBaseline = "align-items-lg-baseline",
    alignItemsLgStretch = "align-items-lg-stretch",
    alignItemsXlStart = "align-items-xl-start",
    alignItemsXlEnd = "align-items-xl-end",
    alignItemsXlCenter = "align-items-xl-center",
    alignItemsXlBaseline = "align-items-xl-baseline",
    alignItemsXlStretch = "align-items-xl-stretch",
    alignItemsXxlStart = "align-items-xxl-start",
    alignItemsXxlEnd = "align-items-xxl-end",
    alignItemsXxlCenter = "align-items-xxl-center",
    alignItemsXxlBaseline = "align-items-xxl-baseline",
    alignItemsXxlStretch = "align-items-xxl-stretch",

}