export enum Mrbr_UI_Bootstrap_Utilities_SpacingMargin {
    margin0 = "m-0",
    margin1 = "m-1",
    margin2 = "m-2",
    margin3 = "m-3",
    margin4 = "m-4",
    margin5 = "m-5",
    marginAuto = "m-auto",

    marginTop0 = "mt-0",
    marginTop1 = "mt-1",
    marginTop2 = "mt-2",
    marginTop3 = "mt-3",
    marginTop4 = "mt-4",
    marginTop5 = "mt-5",
    marginTopAuto = "mt-auto",

    marginBottom0 = "mb-0",
    marginBottom1 = "mb-1",
    marginBottom2 = "mb-2",
    marginBottom3 = "mb-3",
    marginBottom4 = "mb-4",
    marginBottom5 = "mb-5",
    marginBottomAuto = "mb-auto",

    marginStart0 = "ms-0",
    marginStart1 = "ms-1",
    marginStart2 = "ms-2",
    marginStart3 = "ms-3",
    marginStart4 = "ms-4",
    marginStart5 = "ms-5",
    marginStartAuto = "ms-auto",

    marginEnd0 = "me-0",
    marginEnd1 = "me-1",
    marginEnd2 = "me-2",
    marginEnd3 = "me-3",
    marginEnd4 = "me-4",
    marginEnd5 = "me-5",
    marginEndAuto = "me-auto",

    marginX0 = "mx-0",
    marginX1 = "mx-1",
    marginX2 = "mx-2",
    marginX3 = "mx-3",
    marginX4 = "mx-4",
    marginX5 = "mx-5",
    marginXAuto = "mx-auto",

    marginY0 = "my-0",
    marginY1 = "my-1",
    marginY2 = "my-2",
    marginY3 = "my-3",
    marginY4 = "my-4",
    marginY5 = "my-5",
    marginYAuto = "my-auto"
}