export enum Mrbr_UI_Bootstrap_Utilities_Spacing {
    margin0 = "m-0",
    margin1 = "m-1",
    margin2 = "m-2",
    margin3 = "m-3",
    margin4 = "m-4",
    margin5 = "m-5",
    marginAuto = "m-auto",

    marginTop0 = "mt-0",
    marginTop1 = "mt-1",
    marginTop2 = "mt-2",
    marginTop3 = "mt-3",
    marginTop4 = "mt-4",
    marginTop5 = "mt-5",
    marginTopAuto = "mt-auto",

    marginBottom0 = "mb-0",
    marginBottom1 = "mb-1",
    marginBottom2 = "mb-2",
    marginBottom3 = "mb-3",
    marginBottom4 = "mb-4",
    marginBottom5 = "mb-5",
    marginBottomAuto = "mb-auto",

    marginStart0 = "ms-0",
    marginStart1 = "ms-1",
    marginStart2 = "ms-2",
    marginStart3 = "ms-3",
    marginStart4 = "ms-4",
    marginStart5 = "ms-5",
    marginStartAuto = "ms-auto",

    marginEnd0 = "me-0",
    marginEnd1 = "me-1",
    marginEnd2 = "me-2",
    marginEnd3 = "me-3",
    marginEnd4 = "me-4",
    marginEnd5 = "me-5",
    marginEndAuto = "me-auto",

    marginX0 = "mx-0",
    marginX1 = "mx-1",
    marginX2 = "mx-2",
    marginX3 = "mx-3",
    marginX4 = "mx-4",
    marginX5 = "mx-5",
    marginXAuto = "mx-auto",

    marginY0 = "my-0",
    marginY1 = "my-1",
    marginY2 = "my-2",
    marginY3 = "my-3",
    marginY4 = "my-4",
    marginY5 = "my-5",
    marginYAuto = "my-auto",

    padding0 = "p-0",
    padding1 = "p-1",
    padding2 = "p-2",
    padding3 = "p-3",
    padding4 = "p-4",
    padding5 = "p-5",
    paddingAuto = "p-auto",

    paddingTop0 = "pt-0",
    paddingTop1 = "pt-1",
    paddingTop2 = "pt-2",
    paddingTop3 = "pt-3",
    paddingTop4 = "pt-4",
    paddingTop5 = "pt-5",
    paddingTopAuto = "pt-auto",

    paddingBottom0 = "pb-0",
    paddingBottom1 = "pb-1",
    paddingBottom2 = "pb-2",
    paddingBottom3 = "pb-3",
    paddingBottom4 = "pb-4",
    paddingBottom5 = "pb-5",
    paddingBottomAuto = "pb-auto",

    paddingStart0 = " ps-0",
    paddingStart1 = " ps-1",
    paddingStart2 = " ps-2",
    paddingStart3 = " ps-3",
    paddingStart4 = " ps-4",
    paddingStart5 = " ps-5",
    paddingStartAuto = "ps-auto",

    paddingEnd0 = " pe-0",
    paddingEnd1 = " pe-1",
    paddingEnd2 = " pe-2",
    paddingEnd3 = " pe-3",
    paddingEnd4 = " pe-4",
    paddingEnd5 = " pe-5",
    paddingEndAuto = "pe-auto",

    paddingX0 = "px-0",
    paddingX1 = "px-1",
    paddingX2 = "px-2",
    paddingX3 = "px-3",
    paddingX4 = "px-4",
    paddingX5 = "px-5",
    paddingXAuto = "px-auto",

    paddingY0 = " py-0",
    paddingY1 = "py-1",
    paddingY2 = "py-2",
    paddingY3 = "py-3",
    paddingY4 = "py-4",
    paddingY5 = "py-5",
    paddingYAuto = "py-auto",

}