
/**
 * Enum of HTML Elements to HTML Tags
 * @date 24/11/2022 - 19:51:34
 *
 * @export
 * @enum {string}
 */
export enum Mrbr_UI_HTML_ElementTags {
    anchor = "a",
    area = "area",
    audio = "audio",
    base = "base",
    body = "body",
    br = "br",
    button = "button",
    canvas = "canvas",
    data = "data",
    dataList = "datalist",
    details = "details",
    dialog = "dialog",
    directory = "dir",
    div = "div",
    dList = "dl",
    embed = "embed",
    fieldSet = "fieldset",
    figcaption = "figcaption",
    figure = "figure",
    font = "font",
    form = "form",
    frame = "frame",
    frameSet = "frameset",
    heading = "h1",
    heading1 = "h1",
    heading2 = "h2",
    heading3 = "h3",
    heading4 = "h4",
    heading5 = "h5",
    heading6 = "h6",
    head = "head",
    hr = "hr",
    html = "html",
    iFrame = "iframe",
    image = "img",
    input = "input",
    label = "label",
    legend = "legend",
    li = "li",
    link = "link",
    marquee = "marquee",
    map = "map",
    media = "media",
    menu = "menu",
    meta = "meta",
    meter = "meter",
    mod = "mod",
    nav = "nav",
    object = "object",
    olist = "ol",
    optGroup = "optgroup",
    option = "option",
    output = "output",
    paragraph = "p",
    param = "param",
    picture = "picture",
    pre = "pre",
    progress = "progress",
    quote = "q",
    script = "script",
    select = "select",
    slot = "slot",
    source = "source",
    span = "span",
    style = "style",
    svg = "svg",
    tableBody = "tbody",
    tableFooter = "tfoot",
    tableHeader = "thead",
    tableCaption = "caption",
    tableCell = "td",
    tableCol = "col",
    tableColGroup = "colgroup",
    table = "table",
    tableRow = "tr",
    tableSection = "tbody",
    template = "template",
    textArea = "textarea",
    time = "time",
    title = "title",
    track = "track",
    ulist = "ul",
    unknown = "unknown",
    video = "video"
}