
/**
 * Enum of HTML Elements to HTML Tags
 * @date 24/11/2022 - 19:51:34
 *
 * @export
 * @enum {number}
 */
export enum Mrbr_UI_HTML_ElementTagEnum {
    "HTMLAnchorElement" = "a",
    "HTMLAreaElement" = "area",
    "HTMLAudioElement" = "audio",
    "HTMLBaseElement" = "base",
    "HTMLBodyElement" = "body",
    "HTMLBRElement" = "br",
    "HTMLButtonElement" = "button",
    "HTMLCanvasElement" = "canvas",
    "HTMLDataElement" = "data",
    "HTMLDataListElement" = "datalist",
    "HTMLDetailsElement" = "details",
    "HTMLDialogElement" = "dialog",
    "HTMLDirectoryElement" = "dir",
    "HTMLDivElement" = "div",
    "HTMLDListElement" = "dl",
    "HTMLEmbedElement" = "embed",
    "HTMLFieldSetElement" = "fieldset",
    "HTMLFontElement" = "font",
    "HTMLFormElement" = "form",
    "HTMLFrameElement" = "frame",
    "HTMLFrameSetElement" = "frameset",
    "HTMLHeadingElement" = "h1",
    "HTMLHeadElement" = "head",
    "HTMLHRElement" = "hr",
    "HTMLHtmlElement" = "html",
    "HTMLIFrameElement" = "iframe",
    "HTMLImageElement" = "img",
    "HTMLInputElement" = "input",
    "HTMLLabelElement" = "label",
    "HTMLLegendElement" = "legend",
    "HTMLLIElement" = "li",
    "HTMLLinkElement" = "link",
    "HTMLMarqueeElement" = "marquee",
    "HTMLMapElement" = "map",
    "HTMLMediaElement" = "media",
    "HTMLMenuElement" = "menu",
    "HTMLMetaElement" = "meta",
    "HTMLMeterElement" = "meter",
    "HTMLModElement" = "mod",
    "HTMLObjectElement" = "object",
    "HTMLOListElement" = "ol",
    "HTMLOptGroupElement" = "optgroup",
    "HTMLOptionElement" = "option",
    "HTMLOutputElement" = "output",
    "HTMLParagraphElement" = "p",
    "HTMLParamElement" = "param",
    "HTMLPictureElement" = "picture",
    "HTMLPreElement" = "pre",
    "HTMLProgressElement" = "progress",
    "HTMLQuoteElement" = "q",
    "HTMLScriptElement" = "script",
    "HTMLSelectElement" = "select",
    "HTMLSlotElement" = "slot",
    "HTMLSourceElement" = "source",
    "HTMLSpanElement" = "span",
    "HTMLStyleElement" = "style",
    "HTMLTableCaptionElement" = "caption",
    "HTMLTableCellElement" = "td",
    "HTMLTableColElement" = "col",
    "HTMLTableElement" = "table",
    "HTMLTableRowElement" = "tr",
    "HTMLTableSectionElement" = "tbody",
    "HTMLTemplateElement" = "template",
    "HTMLTextAreaElement" = "textarea",
    "HTMLTimeElement" = "time",
    "HTMLTitleElement" = "title",
    "HTMLTrackElement" = "track",
    "HTMLUListElement" = "ul",
    "HTMLUnknownElement" = "unknown",
    "HTMLVideoElement" = "video"
}