
/**
 * Enum of HTML Elements to HTML Tags
 * @date 24/11/2022 - 19:51:34
 *
 * @export
 * @enum {string}
 */
export enum Mrbr_UI_HTML_ElementTagEnum {
    Anchor = "a",
    Area = "area",
    Audio = "audio",
    Base = "base",
    Body = "body",
    BR = "br",
    Button = "button",
    Canvas = "canvas",
    Data = "data",
    DataList = "datalist",
    Details = "details",
    Dialog = "dialog",
    Directory = "dir",
    Div = "div",
    DList = "dl",
    Embed = "embed",
    FieldSet = "fieldset",
    Font = "font",
    Form = "form",
    Frame = "frame",
    FrameSet = "frameset",
    Heading = "h1",
    Heading1 = "h1",
    Heading2 = "h2",
    Heading3 = "h3",
    Heading4 = "h4",
    Heading5 = "h5",
    Heading6 = "h6",
    Head = "head",
    HR = "hr",
    Html = "html",
    IFrame = "iframe",
    Image = "img",
    Input = "input",
    Label = "label",
    Legend = "legend",
    LI = "li",
    Link = "link",
    Marquee = "marquee",
    Map = "map",
    Media = "media",
    Menu = "menu",
    Meta = "meta",
    Meter = "meter",
    Mod = "mod",
    Object = "object",
    OList = "ol",
    OptGroup = "optgroup",
    Option = "option",
    Output = "output",
    Paragraph = "p",
    Param = "param",
    Picture = "picture",
    Pre = "pre",
    Progress = "progress",
    Quote = "q",
    Script = "script",
    Select = "select",
    Slot = "slot",
    Source = "source",
    Span = "span",
    Style = "style",
    TableCaption = "caption",
    TableCell = "td",
    TableCol = "col",
    Table = "table",
    TableRow = "tr",
    TableSection = "tbody",
    Template = "template",
    TextArea = "textarea",
    Time = "time",
    Title = "title",
    Track = "track",
    UList = "ul",
    Unknown = "unknown",
    Video = "video"
}